all_stim:
  agglomerative: false
  dbscan: false
  gmm: false
  hdbscan: false
  k-means: true
func:
  agglomerative: false
  dbscan: false
  gmm: false
  hdbscan: false
  k-means: true
only_chirp:
  agglomerative: false
  dbscan: false
  gmm: false
  hdbscan: false
  k-means: true
poly:
  agglomerative: false
  dbscan: false
  gmm: false
  hdbscan: false
  k-means: false
